name: encryption-service

services:
  postgres:
    image: postgres:16-alpine
    container_name: encryption_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ultramegasecret}
      POSTGRES_DB: ${POSTGRES_DB:-messaging_db}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-messaging_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - msngr-network

  app:
    container_name: encryption-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:ultramegasecret@postgres:5432/messaging_db}
      ENCRYPTION_SERVICE_ADDR: ${ENCRYPTION_SERVICE_ADDR:-:8081}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - msngr-network

volumes:
  postgres_data:

networks:
  msngr-network: